### ISSUE TITLE
Happy to help

### ISSUE THREAD

**Issue by ashesfall** [lucidrains/musiclm-pytorch#1]
I've been working on some basic music generation lately. I'm very interested in this implementation and would be happy to contribute in any way. Maybe that's as simple as donating to sustain your work, or it could be contributing code. Just want to put it out there that I support what you're doing and I'm very interested to see an implementation of this in PyTorch.

**Comment by lucidrains** [comment]
@ashesfall hey thanks Michael

it is already nearly done, as the bulk of the architecture uses [AudioLM](https://github.com/lucidrains/audiolm-pytorch) researchers have started training, and I think if you want to contribute, simply training and open sourcing a good soundstream will do the world a big service

the new thing in MusicLM is the use of an audio CLIP, which is used to filter out the generations from the hierarchical transformers

**Comment by lucidrains** [comment]
@ashesfall join Laion if you haven't and start mingling with the real folks

**Comment by ashesfall** [comment]
When you say training a good soundstream, are you referring to this work? https://arxiv.org/abs/2107.03312

I'd definitely be very willing to make an investment in cloud resources for training.

**Comment by ashesfall** [comment]
Oh I see that they have soundstream training instructions in the main AudioLM repo. Is there a dataset you recommend I use? I can probably start a training run this weekend.
