### ISSUE TITLE
Training MuLan

### ISSUE THREAD

**Issue by ukemamaster** [lucidrains/musiclm-pytorch#11]
@lucidrains The dataset for training MuLan in their original [paper](https://arxiv.org/pdf/2208.12415.pdf) seems to be private. So we need to see other options like:  [Free Music Archive (FMA)](https://academictorrents.com/details/dba20c45d4d6fa6453a4e99d2f8a4817893cfb94) dataset. Where the text part of a sample is a list of strings, like: 

`['low quality', 'sustained strings melody', 'soft female vocal', 'mellow piano melody', 'sad', 'soulful', 'ballad']
`

My question is: Which string should we feed to our network along with the audio? One randomly selected string? Or all? Or make pairs of all with the audio to make even more samples?

**Comment by NikonasSimou** [comment]
Maybe we can use chatGPT to generate a free-form text description using these keywords. I tried the following :
```
I have the following labels describing a music piece 
['low quality', 'sustained strings melody', 'soft female vocal', 'mellow piano melody', 'sad', 'soulful', 'ballad'] 
Can you make a free-form text description using those? It should be maximum 3 sentences
```
And got back : 

`This music piece features a soulful and sad ballad with a sustained strings melody as the main instrument. Soft female vocals add to the emotional depth of the song, accompanied by a mellow piano melody that creates a melancholic atmosphere. Despite being labeled as low quality, the emotional impact of the performance remains strong.`

**Comment by ukemamaster** [comment]
@NikonasSimou Good idea, but i am not sure how can we automate it for a dataset of 100K samples? 

On the otherhand, is there a problem in feeding directly the list of words, removing the commas, and having spaces in between the words? like suggested by @ahanikotb ? 

For example : 

The aspect list: 

`['low quality', 'sustained strings melody', 'soft female vocal', 'mellow piano melody', 'sad', 'soulful', 'ballad']` 

feeding to the model as: 

`low quality sustained strings melody soft female vocal mellow piano melody sad soulful ballad`

**Comment by NikonasSimou** [comment]
I think it could be easily automated using OpenAI's API for gpt. 
Maybe there's no problem with just feeding the keywords separated by commas, but I was thinking that having a free-form text as the paper suggests would be better.

**Comment by ukemamaster** [comment]
And how to convert text input to numbers for feeding into the model?

**Comment by ukemamaster** [comment]
@lucidrains Trying with real music audios and text annotations from their test data. I encountered the following exception: 

```python
Traceback (most recent call last):
  File "train_mulan.py", line 44, in <module>
    trainer.train()
  File "musiclm_pytorch/trainer.py", line 347, in train
    logs = self.train_step()
  File "musiclm_pytorch/trainer.py", line 313, in train_step
    data_kwargs = self.data_tuple_to_kwargs(next(self.dl_iter))
  File "musiclm_pytorch/trainer.py", line 290, in data_tuple_to_kwargs
    assert not has_duplicates(self.ds_fields), 'dataset fields must not have duplicate field names'
AssertionError: dataset fields must not have duplicate field names
```
When i print the `self.ds_fields` in the `trainer.py` it prints: `('wavs', 'wavs')` before the assersion. Could you explain what is meant by `'dataset fields must not have duplicate field names'`?

**Comment by lucidrains** [comment]
> Maybe we can use chatGPT to generate a free-form text description using these keywords. I tried the following :
> 
> ```
> I have the following labels describing a music piece 
> ['low quality', 'sustained strings melody', 'soft female vocal', 'mellow piano melody', 'sad', 'soulful', 'ballad'] 
> Can you make a free-form text description using those? It should be maximum 3 sentences
> ```
> 
> And got back :
> 
> `This music piece features a soulful and sad ballad with a sustained strings melody as the main instrument. Soft female vocals add to the emotional depth of the song, accompanied by a mellow piano melody that creates a melancholic atmosphere. Despite being labeled as low quality, the emotional impact of the performance remains strong.`

inb4 chatgpt based text augmentations become a thing :rofl:

**Comment by lucidrains** [comment]
but yea, a poor-man's augmentation would just be to shuffle that array and join with some delimiter (spaces, commas)

**Comment by lucidrains** [comment]
> @lucidrains Trying with real music audios and text annotations from their test data. I encountered the following exception:
> 
> ```python
> Traceback (most recent call last):
>   File "train_mulan.py", line 44, in <module>
>     trainer.train()
>   File "musiclm_pytorch/trainer.py", line 347, in train
>     logs = self.train_step()
>   File "musiclm_pytorch/trainer.py", line 313, in train_step
>     data_kwargs = self.data_tuple_to_kwargs(next(self.dl_iter))
>   File "musiclm_pytorch/trainer.py", line 290, in data_tuple_to_kwargs
>     assert not has_duplicates(self.ds_fields), 'dataset fields must not have duplicate field names'
> AssertionError: dataset fields must not have duplicate field names
> ```
> 
> When i print the `self.ds_fields` in the `trainer.py` it prints: `('wavs', 'wavs')` before the assersion. Could you explain what is meant by `'dataset fields must not have duplicate field names'`?

what are you returning from your dataset class? you must returning two tensors of type floats, so it doesn't know which one is actually the music / sound https://github.com/lucidrains/musiclm-pytorch/blob/main/musiclm_pytorch/trainer.py#L29

**Comment by lucidrains** [comment]
> I think it could be easily automated using OpenAI's API for gpt. Maybe there's no problem with just feeding the keywords separated by commas, but I was thinking that having a free-form text as the paper suggests would be better.

you should check to make sure this isn't violating some TOS

**Comment by ukemamaster** [comment]
@lucidrains I am returing 2 tensors of type float. 
```
audio size = torch.Size([240000]) 
audio dtype = torch.float32 
text size = torch.Size([256]) 
text dtype = torch.float32
```

Is this correct?

**Comment by lucidrains** [comment]
@ukemamaster ohh, so the text needs to be of type `long`

typically they are token ids that span from 0 to total number of BPE tokens

**Comment by lucidrains** [comment]
@ukemamaster yup, the shapes are fine

**Comment by ukemamaster** [comment]
@lucidrains Yes, it works with type `long`. 
By the way do you have a working example of converting the text into token ids?

**Comment by ukemamaster** [comment]
@lucidrains We use `Accelerate` to prepare the training setup for multi-gpu environment. 
Does it take care of `Pinned_memory` option in the `Dataloader` to speedup training?

**Comment by 0RaMsY0** [comment]
@ukemamaster  How do you pass in the training data to the model, i would like to know how to get started?

**Comment by ishan-kshirsagar0-7** [comment]
@lucidrains Is there any training data available for this? I can't seem to find it anywhere.
