### ISSUE TITLE
Disable the question "do you want to clear previous experiment checkpoints and results? (y/n)" by passing an argument to the trainer

### ISSUE THREAD

**Issue by ukemamaster** [lucidrains/musiclm-pytorch#12]
@lucidrains Hi Phil, can you pass an argument to the `MuLaNTrainer` in `trainer.py` to disable asking the question `"do you want to clear previous experiment checkpoints and results? (y/n)"` every time? 
Otherwise it doesn't proceed to the training, if not answered.

**Comment by lucidrains** [comment]
@ukemamaster oh yea sure, try https://github.com/lucidrains/musiclm-pytorch/commit/af8ff9a28385f711643b46ce1a262c533891f386
