### ISSUE TITLE
'MusicLM' is not defined - cannot run usage commands

### ISSUE THREAD

**Issue by albusdemens** [lucidrains/musiclm-pytorch#13]
When I run your [usage commands](https://github.com/lucidrains/musiclm-pytorch#usage-1), I get the error name `'MusicLM' is not defined` when I run the last snippet (I'm using a Jupyter notebook for that). Am I doing something wrong? Thanks

Here is the Gist with the notebook: https://gist.github.com/albusdemens/cbf06f190b0b519920a09418e0897a4f

**Comment by lucidrains** [comment]
ohh, you need to import `MusicLM`, just updated the readme

you'll also need a trained `AudioLM`, `MuLaN`, and fine-tuned or trained from scratch `AudioLM` with the `MulanEmbedQuantizer`. you won't get music by running the readme at this time

**Comment by albusdemens** [comment]
Thank you so much for the clarification!
