### ISSUE TITLE
Option to use Encodec instead of SoundStream

### ISSUE THREAD

**Issue by Lunariz** [lucidrains/musiclm-pytorch#19]
This tweet suggests that it might be possible to replace SoundStream with the openly available EnCodec:

https://twitter.com/keunwoochoi/status/1620101029399515138

I'm not sure how plausible this is, but EnCodec is even mentioned in the MusicLM paper, and it would save a lot of training effort to be able to use it!

**Comment by lucidrains** [comment]
@Lunariz hey Lukas

i learned that EnCodec has a very restrictive license, non-commercial use

it is probably better to just have the community train a bunch of soundstreams for different domains and share them

**Comment by Lunariz** [comment]
Fair enough, thanks!
