### ISSUE TITLE
"pip install musicml-pytorch" appears to fail on Windows

### ISSUE THREAD

**Issue by onexdata** [lucidrains/musiclm-pytorch#24]
I have Python 3.8.5, Windows 10 latest, tried pip 20.1.1 and 23.0.1 with the same error.

**Comment by Mingxiangyu** [comment]
> 我有 Python 3.8.5，最新的 Windows 10，尝试了 pip 20.1.1 和 23.0.1，但出现了同样的错误。

@onexdata 应该是没问题的，因为我3.9都可以正常安装，你的报错是什么样呢？
