### ISSUE TITLE
Support our open source music pretrained Transformer

### ISSUE THREAD

**Issue by a43992899** [lucidrains/musiclm-pytorch#3]
Hi, we are researchers from the MAP (music audio pre-train) project. We pre-train transformer LMs on large-scale music audio datasets.
See below. Our model, MERT, uses a similar method as HuBERT and has verified its performance on downstream music information retrieval tasks. **It has been released on hugging face and can be used interchangeably with HuBERT loading code:**  `model = HubertModel.from_pretrained("m-a-p/MERT-v0")`
We are currently working on training a better base model and scaling up to a large model with more music+speech data. 
Using our weights as an initialization will be a better start than using speech HuBERT. Better checkpoints will be released soon.

https://huggingface.co/m-a-p/MERT-v0

**Comment by lucidrains** [comment]
@a43992899 hi Ruibin, closing since you asked this also in the audiolm repo
