### ISSUE TITLE
Training data

### ISSUE THREAD

**Issue by JuanuMusic** [lucidrains/musiclm-pytorch#31]
Hi there!
Im trying to train the model using the [MusicCaps](https://www.kaggle.com/datasets/googleai/musiccaps) dataset.

However, on the readme, according to `wavs = torch.randn(2, 1024)` it looks like the audio tensors are 2x1024 (which makes me think it's requiring stereo audio).
The MusicCaps audio is actually mono.

Im not sure if Im correctly interpreting this. Could you give me a hint here?
Thanks!

**Comment by lucidrains** [comment]
@JuanuMusic ohh hey, so that isn't actually stereo, it is batch size of 2

**Comment by JuanuMusic** [comment]
Thanks! Should have thought of that!
Now its training.

Another interesting questin is:
I see a `MuLaNTrainer` but on the readme you mention to train with `mulan(text,text)`

Does that mean I have to `zero_grad` on every step? Is the MulanTrainer user anywherd or is it a WIP?

**Comment by lucidrains** [comment]
@JuanuMusic the zero grad is taken care of for you [here](https://github.com/lucidrains/musiclm-pytorch/blob/main/musiclm_pytorch/trainer.py#L330)

it should work, but i recommend getting onboard efforts at open clip, as they have the infra setup to actually train it at scale

**Comment by jaideep2** [comment]
@JuanuMusic what changes do you made to wavs and text in order to make it compatible with MusicCaps?

**Comment by swap-10** [comment]
I don't understand what's the error I'm making but on running training on musiccaps audio data (tensors with 900k+ elements each) the system is trying to allocate too much memory and crashing (>13GB) even for a small batch (12 samples)
It doesn't crash if I just use 4096 elements in each audio tensor, but that doesn't capture enough information.

@JuanuMusic Could you please share how you got the musiccaps data training with mulan?

Thanks!

**Comment by antoniohof** [comment]
same here
