### ISSUE TITLE
ValueError error when importing the pip package

### ISSUE THREAD

**Issue by dsinkerii** [lucidrains/musiclm-pytorch#40]
Hi there! So im kinda new to all of this, but when i try to import the pip package, i get this error: 
![Снимок экрана_2023-03-31_16-28-20](https://user-images.githubusercontent.com/104655906/229108940-40b27f23-aad5-47c9-b9be-aec57148d064.png)
does anybody know a way to fix this error? Thanks!

**Comment by lucidrains** [comment]
@dsinkerii i don't think pytorch is even compatible with python 3.11

**Comment by lucidrains** [comment]
https://github.com/pytorch/pytorch/issues/86566

**Comment by dsinkerii** [comment]
Oh, i see. I will try to downgrade it and see if this is going to help. Thanks!

**Comment by dsinkerii** [comment]
Yep, that was the issue! thanks!

**Comment by Birch-san** [comment]
> @dsinkerii i don't think pytorch is even compatible with python 3.11

@lucidrains pytorch 2.0 supports python 3.11, except for `torch.compile`. 3.11's JIT makes scripts start faster, so I've been using it a lot.

the problem reported here is unrelated to pytorch.

seems the `@dataclass` decorator from the Python standard library, underwent some kind of breaking change. this line is the one it's complaining about, I think:  
https://github.com/facebookresearch/fairseq/blob/176cd934982212a4f75e0669ee81b834ee71dbb0/fairseq/dataclass/configs.py#L1129

the message says to use a factory for default initialization of fields. probably like this:

```diff
@dataclass
class FairseqConfig(FairseqDataclass):
-     common: CommonConfig = CommonConfig()
+     common: CommonConfig = field(default_factory=CommonConfig)
```

this is a Python 3.11 compatibility problem that needs to be raised against [facebookresearch/fairseq](facebookresearch/fairseq).
