### ISSUE TITLE
Explain Usage - perhaps a Jupyter Notebook can help

### ISSUE THREAD

**Issue by DanielShemesh** [lucidrains/musiclm-pytorch#6]
I am not sure how to train the model. Please provide more information, I think a Colab Jupyter notebook would really help

**Comment by DanielShemesh** [comment]
Maybe I'm mistaken and the code wasn't even written yet. Anyway for future usage, some form of documentation can help

**Comment by DhavalW** [comment]
+1 a step by step guide would really help !
